version: '2'
services:
    jhipster3-app:
        image: jhipster3
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster3-mysql:3306/jhipster3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_CACHE_MEMCACHED_SERVERS=jhipster3-memcached:11211
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster3-mysql:
        extends:
            file: mysql.yml
            service: jhipster3-mysql
    jhipster3-memcached:
        extends:
            file: memcached.yml
            service: jhipster3-memcached
